name: Deploy API to Cloud Run

on:
  push:
    branches: [main]
    paths: ['api/**']  # Only deploy when API files change

env:
  PROJECT_ID: vilara-dev
  REGION: us-central1
  SERVICE_NAME: website
  IMAGE_NAME: us-central1-docker.pkg.dev/vilara-dev/vilara-docker/website

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1040930643556/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@vilara-dev.iam.gserviceaccount.com

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --project ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ env.PROJECT_ID }}

      - name: Show deployment URL
        run: |
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format 'value(status.url)' \
            --project ${{ env.PROJECT_ID }}